# Generated by Django 4.1.5 on 2023-12-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racedriverposition',
            name='_points',
        ),
    ]
