# Generated by Django 4.1.5 on 2023-12-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0002_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='name',
            field=models.CharField(default='League 1', max_length=200),
            preserve_default=False,
        ),
    ]
