# Generated by Django 4.1.5 on 2023-12-26 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0002_remove_racedriverposition__points'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaceDriverPosition',
            new_name='RaceResultDriver',
        ),
        migrations.CreateModel(
            name='RaceResultTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1.team')),
            ],
        ),
    ]
