# Generated by Django 4.1.5 on 2023-12-29 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0003_league_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusWeekendEventPredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeekendEventPredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeekendEventPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1.circuit')),
                ('driver_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_4', to='f1.driver')),
                ('driver_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_5', to='f1.driver')),
                ('driver_of_the_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_of_the_day', to='f1.driver')),
                ('fastest_lap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastest_lap', to='f1.driver')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1.league')),
                ('podium_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podium_1', to='f1.driver')),
                ('podium_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podium_2', to='f1.driver')),
                ('podium_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podium_3', to='f1.driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructorPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1.league')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='f1.team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='f1.team')),
                ('team_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_3', to='f1.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonusWeekendPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('over', models.IntegerField(default=0)),
                ('under', models.IntegerField(default=0)),
                ('prediction', models.BooleanField()),
                ('description', models.TextField()),
                ('weekend_event_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1.weekendeventprediction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
