# Generated by Django 4.1.5 on 2023-12-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0003_rename_racedriverposition_raceresultdriver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raceresultdriver',
            old_name='postion',
            new_name='position',
        ),
    ]
