# Generated by Django 4.1.5 on 2023-12-27 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0004_rename_postion_raceresultdriver_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 0, 49, 5, 983282, tzinfo=datetime.timezone.utc), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circuit',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
        migrations.AddField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 0, 49, 18, 801905, tzinfo=datetime.timezone.utc), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
        migrations.AddField(
            model_name='league',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 0, 49, 20, 869217, tzinfo=datetime.timezone.utc), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
        migrations.AddField(
            model_name='qualifiyingresults',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 0, 49, 22, 892298, tzinfo=datetime.timezone.utc), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualifiyingresults',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 0, 49, 24, 522872, tzinfo=datetime.timezone.utc), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceresult',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
        migrations.AddField(
            model_name='raceresultdriver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 0, 49, 26, 86168, tzinfo=datetime.timezone.utc), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceresultdriver',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
        migrations.AddField(
            model_name='raceresultteam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 0, 49, 30, 325165, tzinfo=datetime.timezone.utc), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceresultteam',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
        migrations.AddField(
            model_name='season',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 0, 49, 42, 61515, tzinfo=datetime.timezone.utc), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 0, 49, 44, 613566, tzinfo=datetime.timezone.utc), verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
    ]
