# Generated by Django 4.1.5 on 2023-12-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0005_circuit_created_at_circuit_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1.season'),
        ),
    ]
