# Generated by Django 4.1.5 on 2023-12-29 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0007_rename_points_gained_bonusweekendeventpredictionresult_fantasy_points_gained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f1.season'),
            preserve_default=False,
        ),
    ]
