# Generated by Django 4.1.5 on 2023-12-27 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0007_alter_raceresultdriver_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresultdriver',
            name='position',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.DeleteModel(
            name='RaceResultTeam',
        ),
    ]
