# Generated by Django 4.1.5 on 2023-12-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0008_league_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
